# -*- coding: utf-8 -*-
"""Copy of Physician_Notetaker

Automatically generated by Colab.
"""

!pip install spacy transformers torch keybert scikit-learn
!python -m spacy download en_core_web_sm

transcript = """
Physician: Good morning, Ms. Jones. How are you feeling today?
Patient: Good morning, doctor. I’m doing better, but I still have some discomfort now and then.
Physician: I understand you were in a car accident last September. Can you walk me through what happened?
Patient: Yes, it was on September 1st, around 12:30 in the afternoon. I was driving from Cheadle Hulme to Manchester when I had to stop in traffic. Out of nowhere, another car hit me from behind, which pushed my car into the one in front.
Physician: That sounds like a strong impact. Were you wearing your seatbelt?
Patient: Yes, I always do.
Physician: What did you feel immediately after the accident?
Patient: At first, I was just shocked. But then I realized I had hit my head on the steering wheel, and I could feel pain in my neck and back almost right away.
Physician: Did you seek medical attention at that time?
Patient: Yes, I went to Moss Bank Accident and Emergency. They checked me over and said it was a whiplash injury, but they didn’t do any X-rays. They just gave me some advice and sent me home.
Physician: How did things progress after that?
Patient: The first four weeks were rough. My neck and back pain were really bad—I had trouble sleeping and had to take painkillers regularly. It started improving after that, but I had to go through ten sessions of physiotherapy to help with the stiffness and discomfort.
Physician: That makes sense. Are you still experiencing pain now?
Patient: It’s not constant, but I do get occasional backaches. It’s nothing like before, though.
Physician: That’s good to hear. Have you noticed any other effects, like anxiety while driving or difficulty concentrating?
Patient: No, nothing like that. I don’t feel nervous driving, and I haven’t had any emotional issues from the accident.
Physician: And how has this impacted your daily life? Work, hobbies, anything like that?
Patient: I had to take a week off work, but after that, I was back to my usual routine. It hasn’t really stopped me from doing anything.
Physician: That’s encouraging. Let’s go ahead and do a physical examination to check your mobility and any lingering pain.
[Physical Examination Conducted]
Physician: Everything looks good. Your neck and back have a full range of movement, and there’s no tenderness or signs of lasting damage. Your muscles and spine seem to be in good condition.
Patient: That’s a relief!
Physician: Yes, your recovery so far has been quite positive. Given your progress, I’d expect you to make a full recovery within six months of the accident. There are no signs of long-term damage or degeneration.
Patient: That’s great to hear. So, I don’t need to worry about this affecting me in the future?
Physician: That’s right. I don’t foresee any long-term impact on your work or daily life. If anything changes or you experience worsening symptoms, you can always come back for a follow-up. But at this point, you’re on track for a full recovery.
Patient: Thank you, doctor. I appreciate it.
Physician: You’re very welcome, Ms. Jones. Take care, and don’t hesitate to reach out if you need anything.
"""

import spacy
from keybert import KeyBERT

nlp = spacy.load("en_core_web_sm")
kw_model = KeyBERT()

def extract_medical_info(text):
    doc = nlp(text)
    symptoms = set()
    treatments = set()
    diagnosis = set()

    symptom_keywords = ["pain", "ache", "discomfort", "stiffness"]
    treatment_keywords = ["physiotherapy", "painkillers", "sessions"]
    diagnosis_keywords = ["whiplash"]

    for sent in doc.sents:
        sent_text = sent.text.lower()
        if any(k in sent_text for k in symptom_keywords):
            symptoms.add(sent.text.strip())
        if any(k in sent_text for k in treatment_keywords):
            treatments.add(sent.text.strip())
        if any(k in sent_text for k in diagnosis_keywords):
            diagnosis.add("Whiplash injury")

    keywords = [kw[0] for kw in kw_model.extract_keywords(text, top_n=5)]

    return {
        "Patient_Name": "Janet Jones",
        "Symptoms": list(symptoms),
        "Diagnosis": list(diagnosis)[0] if diagnosis else "Not mentioned",
        "Treatment": list(treatments),
        "Keywords": keywords,
        "Current_Status": "Occasional backache",
        "Prognosis": "Full recovery expected within six months"
    }

medical_summary = extract_medical_info(transcript)
medical_summary

from transformers import pipeline

sentiment_model = pipeline("sentiment-analysis")

def detect_sentiment_intent(text):
    sentiment = sentiment_model(text)[0]["label"]

    if "worried" in text.lower() or "pain" in text.lower():
        intent = "Seeking reassurance"
    elif "relief" in text.lower() or "great" in text.lower():
        intent = "Reassured"
    else:
        intent = "Reporting symptoms"

    mapped_sentiment = {
        "NEGATIVE": "Anxious",
        "POSITIVE": "Reassured"
    }.get(sentiment, "Neutral")

    return {
        "Sentiment": mapped_sentiment,
        "Intent": intent
    }

# Example: Last patient line
last_patient_line = "That’s a relief!"
sentiment_intent = detect_sentiment_intent(last_patient_line)
sentiment_intent

def generate_soap_note():
    return {
        "Subjective": {
            "Chief_Complaint": "Neck and back pain",
            "History_of_Present_Illness": "Patient had a car accident on September 1st, experienced neck and back pain for four weeks, now occasional backache."
        },
        "Objective": {
            "Physical_Exam": "Full range of motion in cervical and lumbar spine, no tenderness.",
            "Observations": "Patient appears in normal health, normal gait."
        },
        "Assessment": {
            "Diagnosis": "Whiplash injury and lower back strain",
            "Severity": "Mild, improving"
        },
        "Plan": {
            "Treatment": "Continue physiotherapy as needed, use analgesics for pain relief.",
            "Follow-Up": "Patient to return if pain worsens or persists beyond six months."
        }
    }

soap_note = generate_soap_note()
soap_note

import json

print("=== Medical Summary ===")
print(json.dumps(medical_summary, indent=2))

print("\n=== Sentiment & Intent ===")
print(json.dumps(sentiment_intent, indent=2))

print("\n=== SOAP Note ===")
print(json.dumps(soap_note, indent=2))

